part of 'app.dart';
class SettingsScreen extends StatefulWidget {const SettingsScreen({super.key});@override State<SettingsScreen> createState()=>_SettingsScreenState();}
class _SettingsScreenState extends State<SettingsScreen>{
  late Profile edit;final height=TextEditingController(),initial=TextEditingController(),target=TextEditingController();bool loaded=false,busy=false;
  @override void didChangeDependencies(){super.didChangeDependencies();if(!loaded){edit=Profile.fromJson(AppScope.of(context).profile.toJson());height.text=edit.height>0?decimal(edit.height):'';initial.text=edit.initialWeight>0?decimal(edit.initialWeight):'';target.text=edit.targetWeight>0?decimal(edit.targetWeight):'';loaded=true;}}
  @override void dispose(){height.dispose();initial.dispose();target.dispose();super.dispose();}
  Future<void> _save()async{
    final h=height.text.trim().isEmpty?0.0:number(height.text),w=initial.text.trim().isEmpty?0.0:number(initial.text),t=target.text.trim().isEmpty?0.0:number(target.text);
    if(h==null||(h!=0&&(h<100||h>230))||w==null||(w!=0&&(w<30||w>400))||t==null||(t!=0&&(t<30||t>400))||edit.weekdays.isEmpty){message(context,'Controlla i valori e scegli almeno un giorno.');return;}
    edit.height=h;edit.initialWeight=w;edit.targetWeight=t;setState(()=>busy=true);
    try{await AppScope.of(context).updateProfile(Profile.fromJson(edit.toJson()));if(mounted)message(context,'Profilo salvato.');}catch(e){if(mounted)message(context,'Salvataggio non riuscito: $e');}finally{if(mounted)setState(()=>busy=false);}
  }
  Future<void> _import(AppStore s)async{
    if(s.gps.run!=null || s.draft!=null){message(context,'Concludi la seduta o l’attività GPS prima del ripristino.');return;}
    try{
      final result=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['json'],allowMultiple:false,withData:false);if(result==null)return;final f=result.files.single;
      if(f.path==null || f.size>75*1024*1024)throw const FormatException('Scegli un backup di massimo 75 MB.');
      final j=asMap(jsonDecode(await File(f.path!).readAsString()));Repository.validateBackup(j,s.catalog);if(!mounted)return;final records=(j['documents'] as List).length;
      if(!await confirm(context,'Ripristinare $records registrazioni?','Il backup sostituirà i dati presenti nell’app. Prima esporta una copia di sicurezza. Le tracce ripristinate non avviano il GPS.',action:'Sostituisci dati',destructive:true))return;
      setState(()=>busy=true);await s.repository.restore(j);s.rest.clear();await s.reload();await s.gps.recover(s.runs);if(mounted){loaded=false;didChangeDependencies();setState((){});message(context,'Backup ripristinato.');}
    }catch(e){if(mounted)message(context,'Ripristino non eseguito: $e');}finally{if(mounted)setState(()=>busy=false);}
  }
  @override Widget build(BuildContext context){final s=AppScope.of(context);return Scaffold(appBar:AppBar(title:const Text('Profilo e impostazioni')),body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,4,20,32),children:[
    const SectionTitle('Il tuo percorso'),FCard(child:Column(children:[TextField(controller:height,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Altezza · cm')),const SizedBox(height:12),TextField(controller:initial,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Peso iniziale · kg')),const SizedBox(height:12),TextField(controller:target,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Obiettivo modificabile · kg'))])),
    const SectionTitle('Fase di allenamento'),for(var i=0;i<s.catalog.phases.length;i++)RadioListTile<int>(contentPadding:EdgeInsets.zero,value:i,groupValue:edit.phase,title:Text('Fase ${i+1} · ${s.catalog.phases[i]['name']}'),subtitle:Text('${s.catalog.phases[i]['goal']}'),onChanged:busy?null:(v)=>setState(()=>edit.phase=v!)),
    const SectionTitle('Giorni per i pesi'),Wrap(spacing:6,runSpacing:6,children:[for(var i=1;i<=7;i++)FilterChip(label:Text(const ['Lun','Mar','Mer','Gio','Ven','Sab','Dom'][i-1]),selected:edit.weekdays.contains(i),onSelected:busy?null:(selected)=>setState((){if(selected){edit.weekdays.add(i);}else{edit.weekdays.remove(i);}edit.weekdays.sort();}))]),
    const SectionTitle('Mappa e privacy'),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Sfondo cartografico online'),subtitle:const Text('OpenStreetMap riceve le richieste delle aree visualizzate. Disattivandolo rimane visibile la traccia.'),value:edit.mapTiles,onChanged:busy?null:(v)=>setState(()=>edit.mapTiles=v)),const SizedBox(height:16),FilledButton.icon(onPressed:busy?null:_save,icon:const Icon(Icons.save_outlined),label:Text(busy?'Operazione in corso…':'Salva impostazioni')),
    const SectionTitle('I tuoi dati'),
    ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.upload_file),title:const Text('Esporta backup'),subtitle:const Text('Profilo, sedute, misure, tracce e link video. I filmati locali sono esclusi.'),onTap:busy?null:()async{if(!await confirm(context,'Esportare il backup?','Il file contiene dati del profilo e tracce GPS precise. Conserva la copia in un luogo privato.',action:'Esporta') || !context.mounted)return;try{await s.exportBackup(context);}catch(e){if(context.mounted)message(context,'Esportazione non riuscita: $e');}}),
    ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.download_outlined),title:const Text('Ripristina backup Flutter v2'),onTap:busy?null:()=>_import(s)),
    ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.table_chart_outlined),title:const Text('Esporta serie in CSV'),onTap:busy?null:()async{try{await shareTextFile(context,'zoro-forge-serie.csv',workoutCsv(s),'text/csv');}catch(e){if(context.mounted)message(context,'Esportazione non riuscita: $e');}}),
    const SectionTitle('Informazioni'),
    ExpansionTile(tilePadding:EdgeInsets.zero,title:const Text('Privacy e conservazione'),children:const [Padding(padding:EdgeInsets.only(bottom:16),child:Text('Sedute, misure e tracce sono salvate nel database privato dell’app sul telefono. Nessun account, analytics o invio automatico a un nostro server. Il GPS si avvia soltanto su richiesta; la registrazione attiva utilizza una notifica Android. Pausa e fine interrompono gli aggiornamenti di posizione. I servizi video e cartografici ricevono le normali richieste di rete necessarie alla visualizzazione. Il database non è cifrato separatamente: è protetto dal sistema Android. Disinstallando perdi i dati non esportati. Il backup JSON e i file GPX non sono cifrati.'))]),
    ExpansionTile(tilePadding:EdgeInsets.zero,title:const Text('Video e fonti'),children:[const Padding(padding:EdgeInsets.only(bottom:12),child:Text('Filmati degli autori originali, senza estrazione o redistribuzione. I video YouTube usano il player incorporato; i video caricati dal telefono usano il lettore video Android. La riproduzione online dipende dalla connessione e dalle impostazioni del titolare del video.')),for(final ex in s.catalog.exercises.values.where((e)=>e.videos.isNotEmpty))ListTile(title:Text(ex.name),subtitle:Text('${ex.videos.first['publisher']}'),trailing:const Icon(Icons.open_in_new),onTap:()=>openExternal(context,'${ex.videos.first['url']}'))]),
    ListTile(contentPadding:EdgeInsets.zero,title:const Text('Licenze software'),onTap:()=>showLicensePage(context:context,applicationName:'Zoro Forge',applicationVersion:'2.0.0-beta.2')),
    const SizedBox(height:10),const Text('Zoro Forge 2.0.0-beta.2 · Flutter\nApp personale non affiliata ai titolari di One Piece.\nIl backup della vecchia versione HTML non viene importato automaticamente.',style:TextStyle(fontSize:12,color:muted))
  ])));}
}
